# SITE CONFIGURATION

url: "http://indianfaith.com" # the base hostname & protocol for your site
title: "IndianFaith"
description: "Notes on Leadership. The management of the past is obsolete."
permalink: /:categories-temple/:title/	
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
paginate: 3
paginate_path: "page/:num"
include: ['_pages']
markdown: kramdown




